import 'package:bidmygoldflutter/app/routes/app_pages.dart';
import 'package:bidmygoldflutter/app/translations/app_translations.dart'; // Import translations
import 'package:bidmygoldflutter/app/utils/theme/theme.dart'; // Import theme
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:get/get.dart'; // Import GetX
import 'package:get_storage/get_storage.dart'; // Import GetStorage
import 'package:bidmygoldflutter/app/data/services/notification_service.dart'; // Import Notification Service
import 'package:bidmygoldflutter/app/data/services/auth_service.dart'; // Import Auth Service
import 'package:bidmygoldflutter/app/data/services/qr_service.dart'; // Import QR Service

// Import your Firebase options (this file will be generated by FlutterFire CLI later or you can create it manually based on setup)
// import 'firebase_options.dart';

Future<void> main() async {
  // Make main async
  WidgetsFlutterBinding
      .ensureInitialized(); // Ensure Flutter bindings are initialized

  // --- Firebase Initialization ---
  // Uncomment the line below once you have firebase_options.dart
  // IMPORTANT: If you have the config files placed, uncomment the Firebase.initializeApp below
  // that uses `options`. The `flutterfire configure` command generates firebase_options.dart
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );
  // For now, initializing without options, assuming manual setup is complete.
  await Firebase.initializeApp();
  await GetStorage.init(); // Initialize GetStorage

  // Initialize services
  await initServices();

  runApp(const MyApp());
}

// Initialize all required services
Future<void> initServices() async {
  print('Starting services...');

  // Initialize auth service
  await Get.putAsync(() => AuthService().init());

  // Initialize notification service
  await Get.putAsync(() => NotificationService().init());

  // Initialize QR service
  Get.put(QrService());

  print('All services started.');
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    // Replace MaterialApp with GetMaterialApp
    return GetMaterialApp(
      title: 'app_title'.tr, // Use translation key for title
      translations: AppTranslations(), // Set translations
      locale: const Locale('en', 'US'), // Set default locale (English)
      fallbackLocale: const Locale('en', 'US'), // Set fallback locale
      theme: AppTheme.lightTheme, // Apply the light theme
      // darkTheme: AppTheme.darkTheme, // Optional: Apply dark theme
      // themeMode: ThemeMode.system, // Optional: Set theme mode
      debugShowCheckedModeBanner: false, // Hide debug banner
      initialRoute: AppPages.INITIAL, // Set initial route from AppPages
      getPages: AppPages.routes, // Set routes from AppPages
      // home: const MyHomePage(title: 'Flutter Demo Home Page'), // Remove default home
    );
  }
}

// Remove the default MyHomePage StatefulWidget and _MyHomePageState
// class MyHomePage extends StatefulWidget { ... }
// class _MyHomePageState extends State<MyHomePage> { ... }
